### PR TITLE
Basic prep fix 1

### PR DESCRIPTION
**Pull request by bourgeoa**

### CODE REVIEW

**Comment by bourgeoa** [comment]
LGTM
and conformance tests runed on https://solidcommunity.net:8443

**Comment by CxRes** [comment]
Just waiting for @csarven to check the final commit.

**Comment by CxRes** [comment]
Nothing. @bourgeoa prefers it this way, as it allows him to run CTH with solidcommunity.net when the branch is in the repo. And then he merges that.

**Comment by bourgeoa** [comment]
Yes but not only.
It is in general a bad idea to merge directly in main from an outside branch.
There may be issues and main may be polluted, then you may need to revert.

**Pull request merged**
